apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}
          servicePort: http