name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HELM_EXPERIMENTAL_OCI: 1
      ACRNAME: ${{ secrets.ACRNAME }}
    steps:
      - uses: actions/checkout@v2

      - name: Helm tool installer
        uses: Azure/setup-helm@v1
        with:
          version: 3.7.1
          token: ${{ github.token }}

      - name: Login to ACR
        run: echo $ACRPUSHSECRET | helm registry login $ACRNAME --username $ACRPUSHID --password-stdin
        env:
          ACRPUSHSECRET: ${{ secrets.ACRPUSHSECRET }}
          ACRPUSHID: ${{ secrets.ACRPUSHID }}

      - name: Pack and push
        run: |
          val=$(grep version helm-charts/generic-chart/Chart.yaml)
          vals=($val)
          helm chart save helm-charts/generic-chart $ACRNAME/helm/generic-chart:${version[1]}
          helm chart push helm-charts/generic-chart $ACRNAME/helm/generic-chart:${version[1]}

