name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HELM_EXPERIMENTAL_OCI: 1
    steps:
      - uses: actions/checkout@v2

      - name: Helm tool installer
        uses: Azure/setup-helm@v1
        with:
          version: 3.5.2
          token: ${{ github.token }}

      - name: Login to ACR
        run: echo 123 | helm registry login bjorngoranssoninvest.azurecr.io --username sdasd --password-stdin

